### ISSUE TITLE
Unable to select individual days in the calendar

### ISSUE THREAD

**Issue by mardausdennis** [ME-MarvinE/XCalendar#122]
**Describe the bug**
Hello! I hope you are doing well. I wanted to reach out to you because I am having an issue with the calendar in my app. I am unable to select individual days in the calendar. When I click on a date, I hear a “pop” sound, but it is not selected. I have implemented the Models folder with all the events, downloaded the PropertyChanged.Fody Nuget package, and added the BaseViewModel. I believe that I have followed all the necessary steps, but I am still having this issue.

**Expected behavior**
I should be able to select individual days in the calendar by clicking on them.

**Steps to reproduce OR link to code**

- Open the app.
- Navigate to the Calendar tab.
- Try to select a date by clicking on it.
- Note that the date is not selected, even though you hear a “pop” sound.

**Xamarin Forms or .NET MAUI (If related to UI)**
NET MAUI

**Additional context (Optional)**
I have implemented the Models folder with all the events, downloaded the PropertyChanged.Fody Nuget package, and added the BaseViewModel.

As a reference to my project, please see my Github repo: https://github.com/mardausdennis/ReservationmoduleDisApp24/tree/main/app/DisApp24/DisApp24.

**Comment by ME-MarvinE** [comment]
Adding `x:Name="This"` to the page fixes your issue:

In the samples, there are bindings which use `Source={x:Reference This}` in order to escape the local binding context and reference the binding context of the page. It looks for a VisualElement with `x:Name="This"` but this is not defined anywhere in "CalendarPage.xaml". 

There is also a reference to a namespace that does not exist in your solution and may throw errors when attempting to use it: `xmlns:ViewModels="clr-namespace:XCalendarMauiSample.ViewModels`.

Unrelated, but every time I see XCalendar.Maui used in an actual app I'm reminded of the disappointment I felt when I first observed its terrible speed after porting the plugin to .NET MAUI.

**Comment by mardausdennis** [comment]
You are the G.O.A.T. Thanks for your insanely quick response and thanks for noticing my silly error. Do you maybe have a patreon or something of that kind?

**Comment by ME-MarvinE** [comment]
No, I don't. I looked into GitHub sponsors but couldn't figure that out, maybe Patreon would be the way to go though.

Always happy to help.
