### ISSUE TITLE
Let events or selections visually span across multiple days

### ISSUE THREAD

**Issue by UnreachableCode** [ME-MarvinE/XCalendar#126]
**Is your feature request related to a problem? Please describe.**
Related to either events or the multi-select calendar configuration

**Describe the solution you'd like**
Would it be possible to have selections visually span like this instead of as separate circles? Or maybe is there a way to enable this for our app now? 
![image](https://user-images.githubusercontent.com/1167553/231478124-fa86e9b4-5254-472b-a37b-7a90602134b8.png)

**Describe alternatives you've considered**
Writing my own calendar control, or maybe SyncFusion's calendar.

**Comment by ME-MarvinE** [comment]
How I would do this:

Inherit the default `CalendarDay` class (or implement the `ICalendarDay` interface) and add a property indicating if the day should join to the left or right or both. For example `ConnectsToLeft` and `ConnectsToRight`.

Then update the properties of each day based on your custom conditions. This can be done using the `Calendar`'s `DaysUpdating` event, or you could inherit the `Calendar` and override the `UpdateDay` method.

For the logic, I would assume you would get the index of the day in the Calendar's `Days` collection, subtract 1 from the index for the left day and add 1 to the index for the right day. If the current day's `IsSelected` property is true and the left or right days' `IsSelected` properties are also `true`, set the corresponding `ConnectsToLeft` or `ConnectsToRight` property to `true` for the current day, otherwise, set it to `false`.

Then, I would use a `DayView` inside the `CalendarView`''s `DayTemplate` property and use a DataTrigger on the `ConnectsToLeft` and `ConnectsToRight` properties to set the CornerRadius of each side to be round or not depending on their values.

The only potential issue I see is the DataTriggers not working correctly due to years old issues in XF: [#13571](xamarin/Xamarin.Forms#13571) (see also: [#13369](xamarin/Xamarin.Forms#13369), [#14393](xamarin/Xamarin.Forms#14393)) which are present in and also haven't received any attention in MAUI: [#6849](dotnet/maui#6849) (see also: [#10189](dotnet/maui#10189)) meaning they probably won't be fixed in the next few years either.

Nevertheless, I'll add this implementation as an example in the sample app. I think it will be useful for others.

**Comment by UnreachableCode** [comment]
A phenomenal response. Your approach sounds really solid. I'll try and piece something together.

**Comment by ME-MarvinE** [comment]
Added an example to the sample app in #127

**Comment by ME-MarvinE** [comment]
I've decided not to add this as a default functionality. The example in the sample app should suffice if one wishes to do this themselves.

**Comment by widavies** [comment]
@ME-MarvinE I've submitted a pull request to MAUI for this!
