### ISSUE TITLE
Month Translations?

### ISSUE THREAD

**Issue by AndreaGuarducci** [ME-MarvinE/XCalendar#149]
Hello, thx for u'r work,
is there a way to manually translate month's names?

**Comment by ME-MarvinE** [comment]
Yes, you can use the `NavigationViewTemplate` property of the CalendarView and use a `NavigationView` inside the `ControlTemplate`.

The `NavigationView` has all the properties of a `Label` so you would do the same thing as you would do when manually adding a translation for a `Label` element.

Remember to set the `ForwardsArrowCommand` and `BackwardsArrowCommand` if you want to use those. You can either bind them to the TemplatedParent (so that you can still set them through the CalendarView), or you can bind them using your binding context directly.

A list of the `NavigationView`'s properties can be found on the wiki page [here](https://github.com/ME-MarvinE/XCalendar/wiki/NavigationView-Properties).

**Comment by AndreaGuarducci** [comment]
TY!
