### ISSUE TITLE
Maybe we need add net8.0 framework to maui library.

### ISSUE THREAD

**Issue by migueBarrera** [ME-MarvinE/XCalendar#170]
**I have a maui project that has unit tests. To have unit tests, the maui project has to support net-8.  You can learn more about this here: https://youtu.be/C9vIDLQwc7M?t=169**

**We have to add to the maui library, the net8 framework. This solution is inspired by how this library does it:  https://github.com/hjam40/Camera.MAUI/blob/master/Camera.MAUI/Camera.MAUI.csproj.**

**Any alternative?**

Now, by default, If you have unit tests and add XCalendar, it adds conditions in the csproj like this: 

`	

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-ios'">
	  <PackageReference Include="XCalendar.Maui">
	    <Version>4.5.3</Version>
	  </PackageReference>
	</ItemGroup>

`

Also if you don't hide the using of xcalendar in #if Android, it will fail to run the tests.

@ME-MarvinE . If you see this as a good solution. I can do it myself.

**Comment by scheidtdav** [comment]
I am currently facing this as well and may be able to clarify what @migueBarrera means.
With the current version of XCalendar you will need to have the following added to your csproj file:
```
<ItemGroup>
  <PackageReference Include="XCalendar.Core" Version="4.5.5" />
</ItemGroup>

<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
  <PackageReference Include="XCalendar.Maui" Version="4.5.3" />
</ItemGroup>

<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
  <PackageReference Include="XCalendar.Maui" Version="4.5.3" />
</ItemGroup>
```

This is necessary because a unit-testable MAUI project like the above would target net8, net8-android and net8-ios.
After the change, this whole section would be replaced by just 
```
<ItemGroup>
  <PackageReference Include="XCalendar.Maui" Version="4.5.3" />
</ItemGroup>
```
(Note the change from XCalendar.Core to XCalendar.Maui).

**Comment by ME-MarvinE** [comment]
Ah thanks for explaining, sounds good!
