### ISSUE TITLE
Feature request: add the option to choose specific un-available dates

### ISSUE THREAD

**Issue by ddavid-son** [ME-MarvinE/XCalendar#41]
currently we can specify a range of un-available dates, if there will be an option to select dates with out the limitation of them being one after another it will be a grate help.

thanks in advance, keep up the good work

**Comment by ME-MarvinE** [comment]
If I'm understanding correctly, it sounds like you need to set `SelectionType` to `SelectionType.Single` and `SelectionAction` to `SelectionAction.Replace` in the CalendarView. This will make the user only able to select a single date, and when this is done, the previous selection will be overwritten by it.

**Comment by ddavid-son** [comment]
I will try  to clarify with an example :

assume we are talking about this month, I want to be able to the  22.5 , 27.5 and 29.5 to be un-available dates (i.e. not clickable and with different style to indicate the user they are no available)

currently I can not do it because they don't appear sequentially in the calendar( we can only select  DayRangeMinimumDate and DayRangeMaximumDate to be available instead)

**Comment by ME-MarvinE** [comment]
This is currently possible if you inherit from CalendarDayView.
For example you could add an `InvalidDates` bindable property which you set to a collection in your ViewModel from CalendarView's `DayTemplate` property.
Then just override the 'IsDateTimeOutOfRange' method to return if `DateTime` is present in that collection.

It took me a while to remember that I gave `CalendarDayView` virtual methods exactly for purposes like these so I think the real issue is not having good documentation yet again.

Despite that, I do agree that there should be a way to do this without having to inherit from a control at the very least. I'll look into that. However if you're happy with the solution provided please close the issue.

**Comment by ME-MarvinE** [comment]
In 4.0.0 you can inherit from Calendar<T> in XCalendar.Core namespace and override the `IsDateTimeInvalid` function.

Or set the CalendarView's `DayTemplate` to a CalendarDayView and bind the `IsInvalid` property to something in your ViewModel.
