### ISSUE TITLE
Slow when rendering...

### ISSUE THREAD

**Issue by bautistavirchar** [ME-MarvinE/XCalendar#47]
slow when page is loaded...

**Comment by ME-MarvinE** [comment]
Hi,

I know that generating a view for a day is the most performance heavy operation in the CalendarView. Each day in each row needs to be initialised at least once, after which it is reused to improve performance.

I may end up removing the inheritance of 'FramedLabel' ('BorderedLabel' in MAUI) from 'CalendarDayView' in order to remove the extra 'Frame' control but this would also mean the Border properties of 'CalendarDayView' would have to be removed.

If you have any suggestions to increase speed please feel free to share them or contribute.

**Comment by bautistavirchar** [comment]
thanks I appreciated...

**Comment by langhaoabcd** [comment]
> 
This library is very fast, do you have a reference
[Xamarin.Plugin.Calendar](https://github.com/lilcodelab/Xamarin.Plugin.Calendar)
