### ISSUE TITLE
How to add and refresh events during runtime?

### ISSUE THREAD

**Issue by GaborTheHutt** [ME-MarvinE/XCalendar#50]
First of all I would like to thank you @ME-MarvinE  for the great work!

I cant figure out how to add new events. I had make a minimal example from the EventCalendarExample.
As you can see the event gets listetd but not marked in the calendar.
![Screenshot 2022-06-13 191741](https://user-images.githubusercontent.com/60019588/173410137-0498315d-32fb-45cb-8d39-ab8ea593b043.jpg)

![image](https://user-images.githubusercontent.com/60019588/173410467-bfd360f0-0828-4b2f-9ab6-b0f6f4eb82da.png)

**Comment by ME-MarvinE** [comment]
Okay. Part of the problem was that `SelectedEvents` collection should be udpdated again after adding a new event.

The other part of the problem is that `ICalendarDayResolver` is only used when the Calendar is updating. There is no way to trigger this manually from code.

If this were possible then all you would need to do is subscribe to `Events.CollectionChanged` in the ViewModel and call something like `UpdateCalendarCommand.Execute()` in the delegate.

 I will work on this for the next update. 

A quick work around would be to do something that updates the calendar and then reset it. For example selecting a day and then unselecting it or navigating the calendar then navigating it back.

**Comment by GaborTheHutt** [comment]
Thank you for the detailed answer.
Then I looking forward the next updates even more 😃 

> Yes it does not work.
> 
> I added this to EventCalendarViewModel:
> 
> ```cs
> AddEventCommand = new Command(AddEvent); //(At the beginning of the constructor)
> 
> public ICommand AddEventCommand { get; set; }
> 
> public void AddEvent()
> {
>     Events.Add(new Event() { Title = "Dynamic Event", Description = "I Added this Dynamically", Color = Colors[Random.Next(6)], DateTime = DateTime.Now });
> }
> ```
> 
> and added this in the CollectionView in XAML:
> 
> ```
> <CollectionView.Header>
>     <Button Text="Add an event for today" Command="{Binding AddEventCommand}"/>
> </CollectionView.Header>
> ```

I did nearly the same.

**Comment by ME-MarvinE** [comment]
In 4.0.0 you can now call 'UpdateDays' in the Calendar to force an update of the Calendar's days or you can call `UpdateDay` to force an update of a specific day's properties.

So if we use the example in the sample app again, add a handler to 'Events.CollectionChanged' and call 'EventCalendar.UpdateDays' in the handler.

Alternatively you could have the handler encapsulated in EventCalendar.
